### ISSUE TITLE
Can't compile under Linux

### ISSUE THREAD

**Issue by ghost** [Ricardicus/Little-Space-Game#1]
Just tried to compile it under Linux (*Debian 10 buster*), but it failed:

```
$ make
gcc -I/usr/X11R6/include -L/usr/X11R6/lib -lX11 src/pop.c -o pop
src/pop.c:7:10: fatal error: X11/Shell.h: No such file or directory
 #include <X11/Shell.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:5: all] Error 1
```

I has installed `libx11-dev` package, but should I install some additional packages?

- https://packages.debian.org/buster/libx11-dev

**Comment by Ricardicus** [comment]
Very cool that you check this out.

I will fix this! I'll let you know when it is ready to compile.

**Comment by Ricardicus** [comment]
Try again now!

**Comment by Ricardicus** [comment]
Let me know if it works for you.
